### ISSUE TITLE
Sugestão de update

### ISSUE THREAD

**Issue by MatheusClaubert** [DavidWillian7/Batalha-Interestelar#1]
Achei bem legal o jogo, muito nostálgico, queria poder contribuir com algo nostálgico assim, como sugestão seria interessante colocar alguns bônus de poder pra modificar o ataque e para o boss final a nave sendo posicionada nas laterais nunca vão sofrer ataque seria legal acrescentar algo para fazer o player continuar se movimentando

**Comment by DavidWillian7** [comment]
Obrigado pela sugestão, como é um jogo que fiz a alguns semestres atrás na faculdade ele não esta completo, ainda estou criando algumas coisas.
